-- TrustTrip Supabase PostgreSQL Migration 001
-- Safe, Idempotent, Non-Destructive Migration for Admin Control Website & Core Schema Alignment
-- Target Database: Remote Supabase PostgreSQL

-- ============================================================================
-- 1. ADMIN USERS TABLE (Linked with Supabase Auth)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID, -- References auth.users(id) in Supabase Auth
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ADMIN', -- SUPER_ADMIN, ADMIN, OPERATOR, SUPPORT, MODERATOR, INVENTORY_MANAGER, SUPPORT_MANAGER
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, SUSPENDED
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_admin_email ON public.admin_users (email);
CREATE INDEX IF NOT EXISTS idx_admin_role ON public.admin_users (role);
CREATE INDEX IF NOT EXISTS idx_admin_status ON public.admin_users (status);

-- ============================================================================
-- 2. AUGMENT USERS TABLE SAFELY (Add missing columns if not present)
-- ============================================================================
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS country_code VARCHAR(10);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS full_phone_number VARCHAR(60);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_users_status ON public.users (status);
CREATE INDEX IF NOT EXISTS idx_users_mob ON public.users (mob);

-- ============================================================================
-- 3. AUGMENT COMPLAINTS TABLE SAFELY
-- ============================================================================
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS priority VARCHAR(50) DEFAULT 'MEDIUM'; -- LOW, MEDIUM, HIGH, CRITICAL
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS assigned_to BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS assigned_admin_name VARCHAR(255);
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS admin_response TEXT;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_complaints_status ON public.complaints (status);
CREATE INDEX IF NOT EXISTS idx_complaints_priority ON public.complaints (priority);

-- ============================================================================
-- 4. INVENTORY ITEMS TABLE (Safety Gear & Equipment Inventory)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'General', -- Emergency, Medical, Electronics, Self Defense, Gear
    sku VARCHAR(100) UNIQUE NOT NULL,
    current_stock INT NOT NULL DEFAULT 0,
    minimum_stock INT NOT NULL DEFAULT 10,
    unit VARCHAR(50) DEFAULT 'units',
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    supplier VARCHAR(255) DEFAULT 'TrustTrip Safety Supply',
    status VARCHAR(50) DEFAULT 'IN_STOCK', -- IN_STOCK, LOW_STOCK, OUT_OF_STOCK
    image_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventory_sku ON public.inventory_items (sku);
CREATE INDEX IF NOT EXISTS idx_inventory_status ON public.inventory_items (status);
CREATE INDEX IF NOT EXISTS idx_inventory_category ON public.inventory_items (category);

-- ============================================================================
-- 5. INVENTORY TRANSACTIONS TABLE (Stock Movement Audit Ledger)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- ADD, REMOVE, ADJUST, ORDER_DEDUCT, DAMAGE, EXPIRED, RETURN
    quantity INT NOT NULL,
    previous_stock INT NOT NULL,
    new_stock INT NOT NULL,
    supplier VARCHAR(255),
    batch_number VARCHAR(100),
    expiry_date DATE,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    admin_email VARCHAR(255),
    reason VARCHAR(100), -- Sold, Distributed, Damaged, Expired, Lost, Restock, Manual adjustment
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventory_trans_item ON public.inventory_transactions (item_id, created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_trans_type ON public.inventory_transactions (type);

-- ============================================================================
-- 6. FACILITIES TABLE (Hospitals, Police, Safe Zones, Pharmacies)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'Hospital', -- Hospital, Police Station, Pharmacy, Emergency Services, Tourist Assistance, Safe Haven, Women Safety
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(50),
    opening_hours VARCHAR(100) DEFAULT '24/7',
    is_verified BOOLEAN DEFAULT TRUE,
    status VARCHAR(50) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, UNDER_MAINTENANCE
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_facilities_cat ON public.facilities (category, status);
CREATE INDEX IF NOT EXISTS idx_facilities_status ON public.facilities (status);

-- ============================================================================
-- 7. OFFERS TABLE (Deals, Discounts, Verified Promotions)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    discount VARCHAR(100) NOT NULL DEFAULT '10% OFF',
    image_url TEXT,
    vendor VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'PUBLISHED', -- DRAFT, PUBLISHED, EXPIRED, ARCHIVED
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_offers_status ON public.offers (status);

-- ============================================================================
-- 8. ADMIN SETTINGS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 9. AUDIT LOGS TABLE (Append-Only)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    admin_email VARCHAR(255),
    admin_name VARCHAR(255),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100),
    description TEXT NOT NULL,
    ip_address VARCHAR(100),
    user_agent TEXT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON public.audit_logs (entity_type, entity_id);

-- ============================================================================
-- 10. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    -- admin_users policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_admin_users' AND tablename = 'admin_users') THEN
        CREATE POLICY service_role_all_admin_users ON public.admin_users FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'auth_users_read_own_admin' AND tablename = 'admin_users') THEN
        CREATE POLICY auth_users_read_own_admin ON public.admin_users FOR SELECT TO authenticated USING (auth.uid() = user_id OR email = auth.email());
    END IF;

    -- inventory_items policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_inventory' AND tablename = 'inventory_items') THEN
        CREATE POLICY service_role_all_inventory ON public.inventory_items FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'auth_users_read_inventory' AND tablename = 'inventory_items') THEN
        CREATE POLICY auth_users_read_inventory ON public.inventory_items FOR SELECT TO authenticated, anon USING (true);
    END IF;

    -- inventory_transactions policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_inv_trans' AND tablename = 'inventory_transactions') THEN
        CREATE POLICY service_role_all_inv_trans ON public.inventory_transactions FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;

    -- facilities policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_facilities' AND tablename = 'facilities') THEN
        CREATE POLICY service_role_all_facilities ON public.facilities FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_facilities' AND tablename = 'facilities') THEN
        CREATE POLICY anon_read_facilities ON public.facilities FOR SELECT TO anon, authenticated USING (status = 'ACTIVE');
    END IF;

    -- offers policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_offers' AND tablename = 'offers') THEN
        CREATE POLICY service_role_all_offers ON public.offers FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_offers' AND tablename = 'offers') THEN
        CREATE POLICY anon_read_offers ON public.offers FOR SELECT TO anon, authenticated USING (status = 'PUBLISHED');
    END IF;

    -- admin_settings policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_settings' AND tablename = 'admin_settings') THEN
        CREATE POLICY service_role_all_settings ON public.admin_settings FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;

    -- audit_logs policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_audit' AND tablename = 'audit_logs') THEN
        CREATE POLICY service_role_all_audit ON public.audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ============================================================================
-- 11. INITIAL SEED DATA
-- ============================================================================

-- Seed default admin settings
INSERT INTO public.admin_settings (key, value)
VALUES (
    'general_settings',
    '{"app_name": "TrustTrip", "support_email": "support@trusttrip.com", "support_phone": "+91 800 123 4567", "default_minimum_stock": 10, "session_timeout_minutes": 120, "sos_alert_sound": true}'::jsonb
)
ON CONFLICT (key) DO NOTHING;

-- Seed default safety facilities
INSERT INTO public.facilities (name, category, latitude, longitude, address, phone, opening_hours, is_verified, status)
VALUES
    ('Colaba Police Station', 'Police Station', 18.9168, 72.8277, 'Shaheed Bhagat Singh Road, Colaba, Mumbai', '022-22852737', '24/7', true, 'ACTIVE'),
    ('St. George''s Hospital & Trauma Care', 'Hospital', 18.9398, 72.8368, 'P D''Mello Road, Fort, Mumbai', '022-22620242', '24/7', true, 'ACTIVE'),
    ('Apollo 24/7 Emergency Pharmacy', 'Pharmacy', 18.9280, 72.8320, 'Mahatma Gandhi Road, Fort, Mumbai', '1860-500-0101', '24/7', true, 'ACTIVE'),
    ('Mumbai Tourist Facilitation Centre', 'Tourist Assistance', 18.9220, 72.8340, 'Opp. Gateway of India, Apollo Bandar, Mumbai', '022-22845678', '08:00 AM - 10:00 PM', true, 'ACTIVE'),
    ('Women Safety Safe Haven & Helpdesk', 'Women Safety', 18.9300, 72.8310, 'Churchgate Station Concourse, Mumbai', '1091', '24/7', true, 'ACTIVE')
ON CONFLICT DO NOTHING;

-- Seed default offers
INSERT INTO public.offers (title, description, discount, vendor, start_date, end_date, status, image_url)
VALUES
    ('20% Off Safety Equipment Kits', 'Exclusive seasonal traveler discount on compact first aid and safety siren kits.', '20% OFF', 'TrustTrip Safety Supply', '2026-08-01', '2026-12-31', 'PUBLISHED', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500'),
    ('Certified City Guide Weekend Special', 'Book a top-rated multilingual tour guide with verified safety credentials for 15% off.', '15% OFF', 'Maharashtra Tourism Alliance', '2026-08-15', '2026-10-31', 'PUBLISHED', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500'),
    ('Mountain Trail Emergency Gear Bundle', 'Compact tactical flashlight, emergency whistle, and high-altitude bandage bundle.', 'FLAT ₹250 OFF', 'TrustTrip Outdoors', '2026-08-01', '2026-11-30', 'PUBLISHED', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500')
ON CONFLICT DO NOTHING;

-- Sync safety_equipment into inventory_items if inventory_items is empty
INSERT INTO public.inventory_items (name, category, sku, current_stock, minimum_stock, unit, price, supplier, status, image_url, description)
SELECT 
    name,
    COALESCE(category, 'General'),
    'EQ-' || LPAD(id::text, 4, '0'),
    25,
    5,
    'units',
    price,
    'TrustTrip Safety Supply',
    'IN_STOCK',
    image_url,
    description
FROM public.safety_equipment
ON CONFLICT (sku) DO NOTHING;

-- Synchronize all identity sequences
SELECT setval(pg_get_serial_sequence('public.admin_users', 'id'), COALESCE((SELECT MAX(id) FROM public.admin_users), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.inventory_items', 'id'), COALESCE((SELECT MAX(id) FROM public.inventory_items), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.facilities', 'id'), COALESCE((SELECT MAX(id) FROM public.facilities), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.offers', 'id'), COALESCE((SELECT MAX(id) FROM public.offers), 0) + 1, false);
