-- TrustTrip Supabase PostgreSQL Schema for Admin Control Website
-- Idempotent schema definition for admin tables, extensions, and RLS policies.

-- 1. Admin Users Table (linked with Supabase Auth)
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID, -- References auth.users(id) in Supabase Auth
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ADMIN', -- SUPER_ADMIN, ADMIN, MODERATOR, INVENTORY_MANAGER, SUPPORT_MANAGER
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, SUSPENDED
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

-- 2. Augment existing Users table if columns do not exist
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- 3. Augment existing Complaints table if columns do not exist
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS priority VARCHAR(50) DEFAULT 'MEDIUM'; -- LOW, MEDIUM, HIGH, CRITICAL
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS assigned_to BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS assigned_admin_name VARCHAR(255);
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS admin_response TEXT;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 4. Inventory Items Table
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'General', -- Emergency, Medical, Electronics, Self Defense, Gear
    sku VARCHAR(100) UNIQUE NOT NULL,
    current_stock INT NOT NULL DEFAULT 0,
    minimum_stock INT NOT NULL DEFAULT 10,
    unit VARCHAR(50) DEFAULT 'units',
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    supplier VARCHAR(255) DEFAULT 'TrustTrip Safety Supply',
    status VARCHAR(50) DEFAULT 'IN_STOCK', -- IN_STOCK, LOW_STOCK, OUT_OF_STOCK
    image_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Inventory Transactions (Stock Movement Ledger)
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- ADD, REMOVE, ADJUST, ORDER_DEDUCT, DAMAGE, EXPIRED, RETURN
    quantity INT NOT NULL,
    previous_stock INT NOT NULL,
    new_stock INT NOT NULL,
    supplier VARCHAR(255),
    batch_number VARCHAR(100),
    expiry_date DATE,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    admin_email VARCHAR(255),
    reason VARCHAR(100), -- Sold, Distributed, Damaged, Expired, Lost, Restock, Manual adjustment
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Emergency SOS Incidents Table
CREATE TABLE IF NOT EXISTS public.sos_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    username VARCHAR(255),
    emergency_type VARCHAR(100) NOT NULL DEFAULT 'General SOS', -- Police, Ambulance, Fire, Forest, Harassment, Medical, General SOS
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'ACTIVE', -- ACTIVE, ACKNOWLEDGED, RESOLVED, CANCELLED
    acknowledged_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    acknowledged_admin_name VARCHAR(255),
    acknowledged_at TIMESTAMPTZ,
    resolved_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    resolved_admin_name VARCHAR(255),
    resolved_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Safety & Assistance Facilities Table
CREATE TABLE IF NOT EXISTS public.facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'Hospital', -- Hospital, Police Station, Pharmacy, Emergency Services, Tourist Assistance, Safe Haven
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(50),
    opening_hours VARCHAR(100) DEFAULT '24/7',
    is_verified BOOLEAN DEFAULT TRUE,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Deals & Promotional Offers Table
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    discount VARCHAR(100) NOT NULL DEFAULT '10% OFF',
    image_url TEXT,
    vendor VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'PUBLISHED', -- DRAFT, PUBLISHED, EXPIRED, ARCHIVED
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Admin Platform Settings
CREATE TABLE IF NOT EXISTS public.admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Audit Logs Table (Append-Only)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    admin_email VARCHAR(255),
    admin_name VARCHAR(255),
    action VARCHAR(100) NOT NULL, -- LOGIN, LOGOUT, USER_STATUS_CHANGE, USER_DELETE, INVENTORY_ADD, INVENTORY_REMOVE, SOS_STATUS_UPDATE, COMPLAINT_UPDATE, etc.
    entity_type VARCHAR(100) NOT NULL, -- users, inventory, complaints, sos, guides, facilities, offers, admins, settings
    entity_id VARCHAR(100),
    description TEXT NOT NULL,
    ip_address VARCHAR(100),
    user_agent TEXT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_admin_email ON public.admin_users (email);
CREATE INDEX IF NOT EXISTS idx_inventory_sku ON public.inventory_items (sku);
CREATE INDEX IF NOT EXISTS idx_inventory_status ON public.inventory_items (status);
CREATE INDEX IF NOT EXISTS idx_inventory_trans_item ON public.inventory_transactions (item_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sos_status ON public.sos_incidents (status, created_at);
CREATE INDEX IF NOT EXISTS idx_facilities_cat ON public.facilities (category, status);
CREATE INDEX IF NOT EXISTS idx_offers_status ON public.offers (status);
CREATE INDEX IF NOT EXISTS idx_audit_created ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON public.audit_logs (entity_type, entity_id);

-- Enable Row Level Security (RLS) on all admin tables
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sos_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Service Role has full access)
DO $$ 
BEGIN
    -- admin_users policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_admin_users' AND tablename = 'admin_users') THEN
        CREATE POLICY service_role_all_admin_users ON public.admin_users FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'auth_users_read_own_admin' AND tablename = 'admin_users') THEN
        CREATE POLICY auth_users_read_own_admin ON public.admin_users FOR SELECT TO authenticated USING (auth.uid() = user_id OR email = auth.email());
    END IF;

    -- inventory_items policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_inventory' AND tablename = 'inventory_items') THEN
        CREATE POLICY service_role_all_inventory ON public.inventory_items FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'auth_users_read_inventory' AND tablename = 'inventory_items') THEN
        CREATE POLICY auth_users_read_inventory ON public.inventory_items FOR SELECT TO authenticated USING (true);
    END IF;

    -- inventory_transactions policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_inv_trans' AND tablename = 'inventory_transactions') THEN
        CREATE POLICY service_role_all_inv_trans ON public.inventory_transactions FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;

    -- sos_incidents policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_sos' AND tablename = 'sos_incidents') THEN
        CREATE POLICY service_role_all_sos ON public.sos_incidents FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;

    -- facilities policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_facilities' AND tablename = 'facilities') THEN
        CREATE POLICY service_role_all_facilities ON public.facilities FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_facilities' AND tablename = 'facilities') THEN
        CREATE POLICY anon_read_facilities ON public.facilities FOR SELECT TO anon, authenticated USING (status = 'ACTIVE');
    END IF;

    -- offers policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_offers' AND tablename = 'offers') THEN
        CREATE POLICY service_role_all_offers ON public.offers FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_offers' AND tablename = 'offers') THEN
        CREATE POLICY anon_read_offers ON public.offers FOR SELECT TO anon, authenticated USING (status = 'PUBLISHED');
    END IF;

    -- admin_settings policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_settings' AND tablename = 'admin_settings') THEN
        CREATE POLICY service_role_all_settings ON public.admin_settings FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;

    -- audit_logs policies (append only for admins, full for service role)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_audit' AND tablename = 'audit_logs') THEN
        CREATE POLICY service_role_all_audit ON public.audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END $$;
