-- TrustTrip Supabase PostgreSQL Schema
-- Migration from MySQL to PostgreSQL / Supabase

-- 1. Users table
CREATE TABLE IF NOT EXISTS public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    mob VARCHAR(50),
    address TEXT,
    nationality VARCHAR(100),
    emergency_contact VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Complaints table
CREATE TABLE IF NOT EXISTS public.complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(50) DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Guide tables
CREATE TABLE IF NOT EXISTS public.guide (
    g_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    languages VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Available',
    rating DOUBLE PRECISION DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS public.guide_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    guide_id BIGINT NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    CONSTRAINT uq_user_guide UNIQUE (username, guide_id)
);

CREATE TABLE IF NOT EXISTS public.guide_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    guide_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'Booked',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Equipment & Price tables
CREATE TABLE IF NOT EXISTS public.safety_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    price NUMERIC(10,2) NOT NULL,
    description TEXT,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS public.price_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    base_price NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    total_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(50) DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Geo & Crowd tracking tables
CREATE TABLE IF NOT EXISTS public.geo_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    radius_meters INT NOT NULL DEFAULT 500,
    capacity INT NOT NULL DEFAULT 1000,
    status VARCHAR(50) DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS public.user_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    location_id BIGINT,
    seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS public.crowd_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL,
    crowd_count INT NOT NULL,
    capacity INT NOT NULL,
    occupancy_percentage INT NOT NULL,
    crowd_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS public.crowd_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) UNIQUE NOT NULL,
    value VARCHAR(255) NOT NULL
);

-- 6. Device & Notification tables
CREATE TABLE IF NOT EXISTS public.user_devices (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    push_token VARCHAR(500) NOT NULL UNIQUE,
    device_type VARCHAR(50) NOT NULL DEFAULT 'android',
    device_name VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    device_id BIGINT REFERENCES public.user_devices(device_id) ON DELETE SET NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    body TEXT,
    data JSONB,
    is_read BOOLEAN DEFAULT FALSE,
    expo_response_status VARCHAR(50),
    expo_ticket_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Razorpay Payments table
CREATE TABLE IF NOT EXISTS public.razorpay_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razorpay_order_id VARCHAR(100) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR(100) UNIQUE,
    razorpay_signature VARCHAR(128),
    user_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    amount_paise BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'INR',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    receipt VARCHAR(100) NOT NULL UNIQUE,
    failure_reason VARCHAR(500),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_webhook_event VARCHAR(80),
    webhook_received_at TIMESTAMPTZ
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_seen ON public.user_locations (user_id, seen_at);
CREATE INDEX IF NOT EXISTS idx_location_seen ON public.user_locations (location_id, seen_at);
CREATE INDEX IF NOT EXISTS idx_user_active ON public.user_devices (user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_push_token ON public.user_devices (push_token);
CREATE INDEX IF NOT EXISTS idx_user_created ON public.notifications (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_unread ON public.notifications (is_read, created_at);
CREATE INDEX IF NOT EXISTS idx_payment_user ON public.razorpay_payments (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payment_status ON public.razorpay_payments (status, created_at);

-- 8. Identity sequence synchronizer function
CREATE OR REPLACE FUNCTION public.reset_all_sequences()
RETURNS void AS $$
BEGIN
    PERFORM setval(pg_get_serial_sequence('public.users', 'user_id'), COALESCE((SELECT MAX(user_id) FROM public.users), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.complaints', 'id'), COALESCE((SELECT MAX(id) FROM public.complaints), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.guide', 'g_id'), COALESCE((SELECT MAX(g_id) FROM public.guide), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.guide_ratings', 'id'), COALESCE((SELECT MAX(id) FROM public.guide_ratings), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.guide_bookings', 'id'), COALESCE((SELECT MAX(id) FROM public.guide_bookings), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.safety_equipment', 'id'), COALESCE((SELECT MAX(id) FROM public.safety_equipment), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.price_items', 'id'), COALESCE((SELECT MAX(id) FROM public.price_items), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.equipment_orders', 'id'), COALESCE((SELECT MAX(id) FROM public.equipment_orders), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.geo_locations', 'location_id'), COALESCE((SELECT MAX(location_id) FROM public.geo_locations), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.user_locations', 'id'), COALESCE((SELECT MAX(id) FROM public.user_locations), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.crowd_snapshots', 'id'), COALESCE((SELECT MAX(id) FROM public.crowd_snapshots), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.crowd_settings', 'id'), COALESCE((SELECT MAX(id) FROM public.crowd_settings), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.user_devices', 'device_id'), COALESCE((SELECT MAX(device_id) FROM public.user_devices), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.notifications', 'notification_id'), COALESCE((SELECT MAX(notification_id) FROM public.notifications), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public.razorpay_payments', 'id'), COALESCE((SELECT MAX(id) FROM public.razorpay_payments), 0) + 1, false);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Execute sequence reset now
SELECT public.reset_all_sequences();
